### ISSUE TITLE
Enhancement: project update & commit

### ISSUE THREAD

**Issue by redfellow** [brunomgalmeida/rabbitvcs-svn#3]
Would be nice if you added commands SVN:updateProject and SVN:commitProject that use atom.project.getPaths()[0] to get the project root folder for easy an easy projectwide update/commit.

**Comment by redfellow** [comment]
Oh, forgot to add that it's been a while since I made a pull request for you implementing all the functionality I proposed. The only reason I created this ticket is that it's inconvenient to modify the code manually each time the plugin is updated.

https://github.com/brunomgalmeida/rabbitvcs-svn/pulls

**Comment by brunomgalmeida** [comment]
Apologies for the late reply, I only realised now that there were pending commits on this project. 
I have merged your pull request.
Many thanks for your contribution
